package jenkins;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.lessThanOrEqualTo;
import static org.hamcrest.Matchers.notNullValue;

public class newJob extends Login{



    @Test
    public void newjob(){
        System.out.println("------------new job----------");
        Response response1 = given()
                .log().all()
                .filter(sessionFilter)
                .spec(requestSpecification)
        .when()
                .get("/view/all/newJob")
        .then()
                .statusCode(200)
//                .log().all()
                .extract().response();

        System.out.println("------------new itemCategories----------");
        Response response2 = given()
                .log().all()
                .filter(sessionFilter)
                .spec(requestSpecification)
                .when()
                .get("/view/all/itemCategories?depth=3&iconStyle=icon-xlg")
                .then()
                .statusCode(200)
//                .log().all()
                .body("_class",equalTo("jenkins.model.item_category.Categories"))
//                .body("categories",lessThanOrEqualTo(2))
                .extract().response();
    }



    @Test
    public void createJob(){
        given().log().all()
                .filter(sessionFilter)
                .spec(requestSpecification)
                .formParam("name",name)
                .formParam("mode","hudson.model.FreeStyleProject")
                .formParam("from","")
                .formParam("Jenkins-Crumb","abc59ae2f0592643f26b9aba63b9afb7")
                .formParam("json","%7B%22name%22%3A+%22wulei_test%22%2C+%22mode%22%3A+%22hudson.model.FreeStyleProject%22%2C+%22from%22%3A+%22%22%2C+%22Jenkins-Crumb%22%3A+%22abc59ae2f0592643f26b9aba63b9afb7%22%7D")
        .when()
                .post("/view/all/createItem")
        .then()
                .statusCode(302)
                .header("Location",equalTo(RestAssured.baseURI+"/job/"+name+"/configure"))
                .extract().response();

        System.out.println("----------------open configJob-----------");

        given().log().all()
                .filter(sessionFilter)
                .spec(requestSpecification)
        .when()
                .get("/job/"+name+"/configure")
        .then()
                .statusCode(200)
        ;
    }



//    @Test
//    public void submitjob(){
//        Response response1 = given()
//                .filter(sessionFilter)
//                .spec(requestSpecification)
//                .formParam("name",name)
//                .formParam("description","")
//                .formParam("stapler-class-bag","true")
//                .formParam("_.projectUrlStr","")
//                .formParam("_.displayName","")
//                .formParam("_.count","1")
//                .formParam("_.durationName","hour")
//                .formParam("_.daysToKeepStr","")
//                .formParam("_.numToKeepStr","")
//                .formParam("_.artifactDaysToKeepStr","")
//                .formParam("_.artifactNumToKeepStr","")
//                .formParam("stapler-class","hudson.tasks.LogRotator")
//                .formParam("%24class","hudson.tasks.LogRotator")
//                .formParam("_.label","")
//                .formParam("quiet_period","5")
//                .formParam("scmCheckoutRetryCount","0")
//                .formParam("_.customWorkspace","")
//                .formParam("_.displayNameOrNull","")
//                .formParam("scm","0")
//                .formParam("stapler-class","hudson.scm.NullSCM")
//                .formParam("%24class","hudson.scm.NullSCM")
//                .formParam("stapler-class","hudson.plugins.git.GitSCM")
//                .formParam("%24class","hudson.plugins.git.GitSCM")
//                .formParam("_.url","")
//                .formParam("_.credentialsId","")
//                .formParam("_.name","")
//                .formParam("_.refspec","")
//                .formParam("_.name","*%2Fmaster")
//                .formParam("stapler-class","hudson.plugins.git.browser.AssemblaWeb")
//                .formParam("%24class","hudson.plugins.git.browser.AssemblaWeb")
//                .formParam("stapler-class","hudson.plugins.git.browser.FisheyeGitRepositoryBrowser")
//                .formParam("%24class","hudson.plugins.git.browser.FisheyeGitRepositoryBrowser")
//                .formParam("stapler-class","hudson.plugins.git.browser.KilnGit")
//                .formParam("%24class","hudson.plugins.git.browser.KilnGit")
//                .formParam("stapler-class","hudson.plugins.git.browser.TFS2013GitRepositoryBrowser")
//                .formParam("%24class","hudson.plugins.git.browser.TFS2013GitRepositoryBrowser")
//                .formParam("stapler-class","hudson.plugins.git.browser.BitbucketWeb")
//                .formParam("%24class","hudson.plugins.git.browser.BitbucketWeb")
//                .formParam("stapler-class","hudson.plugins.git.browser.CGit")
//                .formParam("%24class","hudson.plugins.git.browser.CGit")
//                .formParam("stapler-class","hudson.plugins.git.browser.GitBlitRepositoryBrowser")
//                .formParam("%24class","hudson.plugins.git.browser.GitBlitRepositoryBrowser")
//                .formParam("stapler-class","hudson.plugins.git.browser.GithubWeb")
//                .formParam("%24class","hudson.plugins.git.browser.GithubWeb")
//                .formParam("stapler-class","hudson.plugins.git.browser.Gitiles")
//                .formParam("%24class","hudson.plugins.git.browser.Gitiles")
//                .formParam("stapler-class","hudson.plugins.git.browser.GitLab")
//                .formParam("%24class","hudson.plugins.git.browser.GitLab")
//                .formParam("stapler-class","hudson.plugins.git.browser.GitList")
//                .formParam("%24class","hudson.plugins.git.browser.GitList")
//                .formParam("stapler-class","hudson.plugins.git.browser.GitoriousWeb")
//                .formParam("%24class","hudson.plugins.git.browser.GitoriousWeb")
//                .formParam("stapler-class","hudson.plugins.git.browser.GitWeb")
//                .formParam("%24class","hudson.plugins.git.browser.GitWeb")
//                .formParam("stapler-class","hudson.plugins.git.browser.GogsGit")
//                .formParam("%24class","hudson.plugins.git.browser.GogsGit")
//                .formParam("stapler-class","hudson.plugins.git.browser.Phabricator")
//                .formParam("%24class","hudson.plugins.git.browser.Phabricator")
//                .formParam("stapler-class","hudson.plugins.git.browser.RedmineWeb")
//                .formParam("%24class","hudson.plugins.git.browser.RedmineWeb")
//                .formParam("stapler-class","hudson.plugins.git.browser.RhodeCode")
//                .formParam("%24class","hudson.plugins.git.browser.RhodeCode")
//                .formParam("stapler-class","hudson.plugins.git.browser.Stash")
//                .formParam("%24class","hudson.plugins.git.browser.Stash")
//                .formParam("stapler-class","hudson.plugins.git.browser.ViewGitWeb")
//                .formParam("%24class","hudson.plugins.git.browser.ViewGitWeb")
//                .formParam("stapler-class","hudson.scm.SubversionSCM")
//                .formParam("%24class","hudson.scm.SubversionSCM")
//                .formParam("_.remote","")
//                .formParam("_.credentialsId","")
//                .formParam("_.local",".")
//                .formParam("depthOption","infinity")
//                .formParam("_.ignoreExternalsOption","on")
//                .formParam("_.cancelProcessOnExternalsFail","on")
//                .formParam("stapler-class","hudson.scm.subversion.UpdateUpdater")
//                .formParam("%24class","hudson.scm.subversion.UpdateUpdater")
//                .formParam("stapler-class","hudson.scm.subversion.CheckoutUpdater")
//                .formParam("%24class","hudson.scm.subversion.CheckoutUpdater")
//                .formParam("stapler-class","hudson.scm.subversion.NoopUpdater")
//                .formParam("%24class","hudson.scm.subversion.NoopUpdater")
//                .formParam("stapler-class","hudson.scm.subversion.UpdateWithCleanUpdater")
//                .formParam("%24class","hudson.scm.subversion.UpdateWithCleanUpdater")
//                .formParam("stapler-class","hudson.scm.subversion.UpdateWithRevertUpdater")
//                .formParam("%24class","hudson.scm.subversion.UpdateWithRevertUpdater")
//                .formParam("_.quietOperation","on")
//                .formParam("stapler-class","hudson.scm.browsers.Assembla")
//                .formParam("%24class","hudson.scm.browsers.Assembla")
//                .formParam("stapler-class","hudson.scm.browsers.CollabNetSVN")
//                .formParam("%24class","hudson.scm.browsers.CollabNetSVN")
//                .formParam("stapler-class","hudson.scm.browsers.FishEyeSVN")
//                .formParam("%24class","hudson.scm.browsers.FishEyeSVN")
//                .formParam("stapler-class","hudson.scm.browsers.Phabricator")
//                .formParam("%24class","hudson.scm.browsers.Phabricator")
//                .formParam("stapler-class","hudson.scm.browsers.SVNWeb")
//                .formParam("%24class","hudson.scm.browsers.SVNWeb")
//                .formParam("stapler-class","hudson.scm.browsers.Sventon")
//                .formParam("%24class","hudson.scm.browsers.Sventon")
//                .formParam("stapler-class","hudson.scm.browsers.Sventon2")
//                .formParam("%24class","hudson.scm.browsers.Sventon2")
//                .formParam("stapler-class","hudson.scm.browsers.ViewSVN")
//                .formParam("%24class","hudson.scm.browsers.ViewSVN")
//                .formParam("stapler-class","hudson.scm.browsers.VisualSVN")
//                .formParam("%24class","hudson.scm.browsers.VisualSVN")
//                .formParam("stapler-class","hudson.scm.browsers.WebSVN")
//                .formParam("%24class","hudson.scm.browsers.WebSVN")
//                .formParam("_.excludedRegions","")
//                .formParam("_.includedRegions","")
//                .formParam("_.excludedUsers","")
//                .formParam("_.excludedCommitMessages","")
//                .formParam("_.excludedRevprop","")
//                .formParam("authToken","")
//                .formParam("_.upstreamProjects","")
//                .formParam("ReverseBuildTrigger.threshold","SUCCESS")
//                .formParam("_.spec","")
//                .formParam("_.scmpoll_spec","")
//                .formParam("_.cleanupParameter","")
//                .formParam("_.externalDelete","")
//                .formParam("_.timeoutMinutes","3")
//                .formParam("stapler-class","hudson.plugins.build_timeout.impl.AbsoluteTimeOutStrategy")
//                .formParam("%24class","hudson.plugins.build_timeout.impl.AbsoluteTimeOutStrategy")
//                .formParam("stapler-class","hudson.plugins.build_timeout.impl.DeadlineTimeOutStrategy")
//                .formParam("%24class","hudson.plugins.build_timeout.impl.DeadlineTimeOutStrategy")
//                .formParam("stapler-class","hudson.plugins.build_timeout.impl.ElasticTimeOutStrategy")
//                .formParam("%24class","hudson.plugins.build_timeout.impl.ElasticTimeOutStrategy")
//                .formParam("stapler-class","hudson.plugins.build_timeout.impl.LikelyStuckTimeOutStrategy")
//                .formParam("%24class","hudson.plugins.build_timeout.impl.LikelyStuckTimeOutStrategy")
//                .formParam("stapler-class","hudson.plugins.build_timeout.impl.NoActivityTimeOutStrategy")
//                .formParam("%24class","hudson.plugins.build_timeout.impl.NoActivityTimeOutStrategy")
//                .formParam("_.timeoutEnvVar","").formParam("core%3Aapply","")
//                .formParam("Jenkins-Crumb","abc59ae2f0592643f26b9aba63b9afb7")
//                .formParam("json","%7B%22name%22%3A+%22wulei_test%22%2C+%22description%22%3A+%22%22%2C+%22properties%22%3A+%7B%22stapler-class-bag%22%3A+%22true%22%2C+%22com-coravy-hudson-plugins-github-GithubProjectProperty%22%3A+%7B%7D%2C+%22jenkins-branch-RateLimitBranchProperty%24JobPropertyImpl%22%3A+%7B%7D%2C+%22jenkins-model-BuildDiscarderProperty%22%3A+%7B%22specified%22%3A+false%2C+%22%22%3A+%220%22%2C+%22strategy%22%3A+%7B%22daysToKeepStr%22%3A+%22%22%2C+%22numToKeepStr%22%3A+%22%22%2C+%22artifactDaysToKeepStr%22%3A+%22%22%2C+%22artifactNumToKeepStr%22%3A+%22%22%2C+%22stapler-class%22%3A+%22hudson.tasks.LogRotator%22%2C+%22%24class%22%3A+%22hudson.tasks.LogRotator%22%7D%7D%2C+%22hudson-model-ParametersDefinitionProperty%22%3A+%7B%22specified%22%3A+false%7D%7D%2C+%22disable%22%3A+false%2C+%22concurrentBuild%22%3A+false%2C+%22hasSlaveAffinity%22%3A+false%2C+%22label%22%3A+%22%22%2C+%22hasCustomQuietPeriod%22%3A+false%2C+%22quiet_period%22%3A+%225%22%2C+%22hasCustomScmCheckoutRetryCount%22%3A+false%2C+%22scmCheckoutRetryCount%22%3A+%220%22%2C+%22blockBuildWhenUpstreamBuilding%22%3A+false%2C+%22blockBuildWhenDownstreamBuilding%22%3A+false%2C+%22hasCustomWorkspace%22%3A+false%2C+%22customWorkspace%22%3A+%22%22%2C+%22displayNameOrNull%22%3A+%22%22%2C+%22scm%22%3A+%7B%22value%22%3A+%220%22%2C+%22stapler-class%22%3A+%22hudson.scm.NullSCM%22%2C+%22%24class%22%3A+%22hudson.scm.NullSCM%22%7D%2C+%22core%3Aapply%22%3A+%22%22%2C+%22Jenkins-Crumb%22%3A+%22abc59ae2f0592643f26b9aba63b9afb7%22%7D")
//                .formParam("Submit","%E4%BF%9D%E5%AD%98")
//        .when()
//                .get("/job/"+name+"/configureSubmit")
//        .then()
//                .statusCode(302)
//                .header("Location",equalTo(RestAssured.baseURI+"/job/"+name+"/"))
//                .extract().response();
//    }
}
